[package]
name = "displayarray"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.6"
image = "0.23"
rand = "0.8.4"
minifb = "0.19"
